---
- name: Get non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_facts.env.SUDO_USER }}"
  tags:
    - clean
- name: Add existing user '{{ remote_regular_user }}' to group docker
  user:
    name: '{{ remote_regular_user }}'
    groups: docker
    append: yes
  become: yes

- name: set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow
  become: yes

- name: Change default bash history size.
  ansible.builtin.replace:
    path: "/home/{{ remote_regular_user }}/.bashrc"
    regexp: '^HISTSIZE=.*$'
    replace: 'HISTSIZE=10000000'

- name: Change default bash history size.
  ansible.builtin.replace:
    path: "/home/{{ remote_regular_user }}/.bashrc"
    regexp: '^HISTFILESIZE=.*$'
    replace: 'HISTFILESIZE=20000000'

- name: Save history even mc is running
  ansible.builtin.blockinfile:
    create: false
    path: "/home/{{ remote_regular_user }}/.bashrc"
    block: |
      export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

- name: add inputrc
  ansible.builtin.blockinfile:
    create: false
    path: /etc/inputrc
    block: |
      "\C-p": history-search-backward
      "\C-n": history-search-forward
  become: yes

- name: Update and upgrade apt packages
  apt:
    upgrade: 'yes'
    update_cache: yes
  become: yes

#- name: Run apt-get update
#  ansible.builtin.apt:
#    update_cache: yes
 # become: yes

- name: Install useful packages
  ansible.builtin.apt: 
    pkg:
      - mc
      - htop
      - iftop
      - iotop
      - bash-completion
      - jq
      - sysstat
      - nload
      - psmisc
      - tree
      - rsync
      - net-tools
    state: present
  become: yes

- name: Uninstall useful packages
  ansible.builtin.apt: 
    pkg:
      - mc
      - htop
      - iftop
      - iotop
      - bash-completion
      - jq
      - sysstat
      - nload
      - psmisc
      - tree
      - rsync
      - net-tools
    state: absent
    purge: yes
  become: yes
  tags:
    - never
    - clean

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
  become: yes
  tags:
    - clean
    - never

- name: add inputrc
  ansible.builtin.blockinfile:
    create: false
    path: /etc/inputrc
    state: absent
    block: |
      "\C-p": history-search-backward
      "\C-n": history-search-forward
  tags:
    - never
    - clean

- name: Get current groups list of "{{ remote_regular_user }}"
  command: groups "{{ remote_regular_user }}"
  register: current_groups
  tags:
    - clean
    - never

- set_fact:
    current_group_list: "{{ current_groups.stdout.replace( remote_regular_user+' : ','').split(' ') }}"
  tags:
    - clean
    - never

- name: Remove user '{{ remote_regular_user }}' from group docker
  user:
    name: '{{ remote_regular_user }}'
    groups: "{{ current_group_list | difference('docker')}}"
    append: no
  become: yes
  tags:
    - never
    - clean
